import type { RootStackParamList, TabParamList } from './types';

/**
 * Canonical stack route names — use with `navigation.navigate(ROUTES.X, …)` so names stay aligned
 * with `RootStackParamList` and `AppNavigator` `Stack.Screen` registrations.
 */
export const ROUTES = {
  Onboarding: 'Onboarding',
  Login: 'Login',
  Register: 'Register',
  ForgotPassword: 'ForgotPassword',
  PublicStudentRegistration: 'PublicStudentRegistration',
  PublicSchoolRegistration: 'PublicSchoolRegistration',
  Main: 'Main',
  NotificationInbox: 'NotificationInbox',
  UserProfile: 'UserProfile',
  CourseDetail: 'CourseDetail',
  AssignmentDetail: 'AssignmentDetail',
  MessageThread: 'MessageThread',
  ChildDetail: 'ChildDetail',
  ParentResults: 'ParentResults',
  ParentAttendance: 'ParentAttendance',
  ParentGrades: 'ParentGrades',
  ParentInvoices: 'ParentInvoices',
  ParentCertificates: 'ParentCertificates',
  ParentFeedback: 'ParentFeedback',
  PeopleHub: 'PeopleHub',
  Students: 'Students',
  StudentImport: 'StudentImport',
  Teachers: 'Teachers',
  Schools: 'Schools',
  Parents: 'Parents',
  ParentDetail: 'ParentDetail',
  Approvals: 'Approvals',
  Attendance: 'Attendance',
  Payments: 'Payments',
  BulkPayments: 'BulkPayments',
  Transactions: 'Transactions',
  Progress: 'Progress',
  IoT: 'IoT',
  Timetable: 'Timetable',
  Classes: 'Classes',
  CBT: 'CBT',
  CBTExamination: 'CBTExamination',
  CBTExamEditor: 'CBTExamEditor',
  CBTGrading: 'CBTGrading',
  Reports: 'Reports',
  StudentDetail: 'StudentDetail',
  TeacherDetail: 'TeacherDetail',
  AddStudent: 'AddStudent',
  AddSchool: 'AddSchool',
  AddTeacher: 'AddTeacher',
  AddClass: 'AddClass',
  SchoolDetail: 'SchoolDetail',
  BulkRegister: 'BulkRegister',
  ClassDetail: 'ClassDetail',
  CreateAssignment: 'CreateAssignment',
  ReportBuilder: 'ReportBuilder',
  StudentReport: 'StudentReport',
  AI: 'AI',
  Assignments: 'Assignments',
  Grades: 'Grades',
  Certificates: 'Certificates',
  Invoices: 'Invoices',
  Messages: 'Messages',
  Settings: 'Settings',
  MyChildren: 'MyChildren',
  Analytics: 'Analytics',
  Courses: 'Courses',
  CourseEditor: 'CourseEditor',
  Projects: 'Projects',
  ProjectDetail: 'ProjectDetail',
  Library: 'Library',
  Leaderboard: 'Leaderboard',
  LiveSessions: 'LiveSessions',
  Engage: 'Engage',
  Vault: 'Vault',
  Playground: 'Playground',
  Portfolio: 'Portfolio',
  Missions: 'Missions',
  Protocol: 'Protocol',
  ManageCertificates: 'ManageCertificates',
  Newsletters: 'Newsletters',
  CardBuilder: 'CardBuilder',
  Users: 'Users',
  EnrolStudents: 'EnrolStudents',
  WipeStudents: 'WipeStudents',
  Programs: 'Programs',
  Lessons: 'Lessons',
  LessonDetail: 'LessonDetail',
  CourseDiscussion: 'CourseDiscussion',
  DiscussionTopic: 'DiscussionTopic',
  LessonEditor: 'LessonEditor',
  SchoolOverview: 'SchoolOverview',
   SchoolBilling: 'SchoolBilling',
  MarkAttendance: 'MarkAttendance',
  ActivityLogs: 'ActivityLogs',
  Subscriptions: 'Subscriptions',
  Moderation: 'Moderation',
  InvoiceEditor: 'InvoiceEditor',
} as const satisfies { [K in keyof RootStackParamList]: K };

export type StackRouteName = (typeof ROUTES)[keyof typeof ROUTES];

export const TAB_ROUTES = {
  Dashboard: 'Dashboard',
  Learn: 'Learn',
  Alerts: 'Alerts',
  MainSignOut: 'MainSignOut',
  AdminPeopleHub: 'AdminPeopleHub',
  AdminPayments: 'AdminPayments',
  AdminSignOut: 'AdminSignOut',
  TeacherMyClass: 'TeacherMyClass',
  TeacherGrading: 'TeacherGrading',
  TeacherSignOut: 'TeacherSignOut',
} as const satisfies { [K in keyof TabParamList]: K };

export type TabRouteName = (typeof TAB_ROUTES)[keyof typeof TAB_ROUTES];

/** First route inside the authenticated `Main` stack (tab shell); not part of `RootStackParamList`. */
export const MAIN_STACK_TABS = 'MainTabs' as const;
