export type RootStackParamList = {
  Onboarding: undefined;
  Login: undefined;
  Register: undefined;
  ForgotPassword: undefined;
  PublicStudentRegistration: undefined;
  PublicSchoolRegistration: undefined;
  Main: undefined;
  // Detail screens (accessible from tabs)
  CourseDetail: { programId: string; title: string };
  AssignmentDetail: { assignmentId: string; title: string };
  MessageThread: { userId: string; name: string };
  ChildDetail: { studentId: string; name: string };
  // Parent portal detail screens
  ParentResults: { studentId: string; studentName?: string };
  ParentAttendance: { studentId: string; studentName?: string };
  ParentGrades: { studentId: string; studentName?: string };
  ParentInvoices: { studentId: string; studentName?: string };
  ParentCertificates: { studentId: string; studentName?: string };
  // Admin / staff screens
  Students: undefined;
  Teachers: undefined;
  Schools: undefined;
  Parents: undefined;
  Approvals: undefined;
  Attendance: undefined;
  Payments: undefined;
  Timetable: undefined;
  Classes: undefined;
  CBT: undefined;
  CBTExamination: { examId: string };
  Reports: undefined;
  StudentDetail: { studentId: string };
  TeacherDetail: { teacherId: string };
  AddStudent: undefined;
  AddSchool: undefined;
  AddTeacher: undefined;
  AddClass: undefined;
  SchoolDetail: { schoolId: string };
  BulkRegister: undefined;
  ClassDetail: { classId: string };
  CreateAssignment: { classId?: string; className?: string };
  ReportBuilder: { studentId?: string; studentName?: string };
  StudentReport: { studentId: string; studentName?: string };
  AI: undefined;
  Assignments: undefined;
  Grades: undefined;
  Certificates: undefined;
  Invoices: undefined;
  Messages: undefined;
  Settings: undefined;
  MyChildren: undefined;
  Analytics: undefined;
  // New screens
  Courses: undefined;
  Projects: undefined;
  Library: undefined;
  Leaderboard: undefined;
  LiveSessions: undefined;
  Engage: undefined;
  Vault: undefined;
  Missions: undefined;
  Protocol: undefined;
  ManageCertificates: undefined;
  Newsletters: undefined;
  CardBuilder: undefined;
  Users: undefined;
  EnrolStudents: undefined;
  WipeStudents: undefined;
  Programs: undefined;
  Lessons: undefined;
  LessonDetail: { lessonId: string };
  SchoolOverview: undefined;
};

export type TabParamList = {
  Dashboard: undefined;
  Learn: undefined;
  Notifications: undefined;
  Profile: undefined;
  Portal: undefined;
};
